### PR TITLE
New restAPIs

### PR DESCRIPTION
**Pull request by TonyJabbour**

### CODE REVIEW

**Comment by TonyJabbour** [comment]
please label this PR "hacktoberfest-accepted"

**Comment by adulau** [comment]
Could you just resolve the conflict with the new sync API feature? before we could merge.

**Comment by adulau** [comment]
@Terrtia Thanks for the merge!

**Comment by Terrtia** [comment]
HI @TonyJabbour !
Thank you very much!   Merged into master.

I renamed two endpoints:
``api/v1/get/item/content/encoded/text`` -> ``api/v1/get/item/content/utf8/base64``
``api/v1/get/item/sources`` -> ``api/v1/get/items/sources``

I removed ``api/v1/get/item/source/check``. I think we should check if a source exists in ail on the client side (with ``api/v1/get/items/sources``)

**Comment by TonyJabbour** [comment]
noted ! thanks

**Pull request merged**
