### PR TITLE
Support ARM aarch64 Device

### PR DESCRIPTION
**Pull request by vncloudsco**
Dear: Team
today I released a version of your software that supports the arm platform, this is an install we have fixed it's fully compatible. we tested it on ARM aarch64 platform

My pc test:
```
Linux instance-dubai3 5.11.0-1021-oracle #22~20.04.1-Ubuntu SMP Fri Oct 22 21:42:24 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

you can use it to run on ARM servers via file installing_arm.sh, 

I built an arm-based docker for this project:  https://hub.docker.com/r/vouu/ail-framework

info login test: 

```
new user created: admin@admin.test
password: ukydeO#7@kzk%E2Mn%xcX9SAmlGf8k
```

### CODE REVIEW

**Comment by adulau** [comment]
FYI, we [just updated](https://github.com/ail-project/ardb/commit/fbe8d0f964395a6d06620fe29646c958b5070706) the rocksdb back-end to be compiled in `PORTABLE` mode. So it should work out-of-the-box for your use-case too. Let's know if this is fine then it would be required to have another ARDB for another architecture.

**Comment by vncloudsco** [comment]
Dear: @adulau 
thank you I will check and report the problem back to you if any.

**Comment by adulau** [comment]
Looking at your changes, it seems it's really related to the ARM port. We cannot merge this as it's custom for your configuration pointing to another custom repository. As we will remove ardb and replace it with [kvrocks](https://github.com/KvrocksLabs/kvrocks), I would propose that you can do tests with kvrocks. But this might need some additional works.

**Comment by vncloudsco** [comment]
Dear: @adulau
1: i have check PORTABLE update from you commit it got error i can't build ARDB
2:  build with kvrocks no improvement

```
util/crc32c.cc:371:1: error: template with C linkage
  371 | template<void (*CRC32)(uint64_t*, uint8_t const**)>
      | ^~~~~~~~
In file included from ./util/crc32c_arm64.h:16,
                 from util/crc32c.cc:21:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_acle.h:33:1: note: ‘extern "C"’ linkage started here
   33 | extern "C" {
      | ^~~~~~~~~~
util/crc32c.cc:503:13: error: conflicting declaration of ‘std::string rocksdb::crc32c::IsFastCrc32Supported()’ with ‘C’ linkage
  503 | std::string IsFastCrc32Supported() {
      |             ^~~~~~~~~~~~~~~~~~~~
In file included from util/crc32c.cc:12:
./util/crc32c.h:20:20: note: previous declaration with ‘C++’ linkage
   20 | extern std::string IsFastCrc32Supported();
      |                    ^~~~~~~~~~~~~~~~~~~~
util/crc32c.cc:1277:10: error: conflicting declaration of ‘uint32_t rocksdb::crc32c::Extend(uint32_t, const char*, size_t)’ with ‘C’ linkage
 1277 | uint32_t Extend(uint32_t crc, const char* buf, size_t size) {
      |          ^~~~~~
In file included from util/crc32c.cc:12:
./util/crc32c.h:25:17: note: previous declaration with ‘C++’ linkage
   25 | extern uint32_t Extend(uint32_t init_crc, const char* data, size_t n);
      |                 ^~~~~~
util/crc32c.cc:1283:1: error: expected ‘}’ at end of input
 1283 | }  // namespace ROCKSDB_NAMESPACE
      | ^
In file included from ./util/crc32c_arm64.h:16,
                 from util/crc32c.cc:21:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_acle.h:33:12: note: to match this ‘{’
   33 | extern "C" {
      |            ^
$DEBUG_LEVEL is 0
  CC       util/crc32c.o
util/crc32c.cc:371:1: error: template with C linkage
  371 | template<void (*CRC32)(uint64_t*, uint8_t const**)>
      | ^~~~~~~~
In file included from ./util/crc32c_arm64.h:16,
                 from util/crc32c.cc:21:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_acle.h:33:1: note: ‘extern "C"’ linkage started here
   33 | extern "C" {
      | ^~~~~~~~~~
util/crc32c.cc:503:13: error: conflicting declaration of ‘std::string rocksdb::crc32c::IsFastCrc32Supported()’ with ‘C’ linkage
  503 | std::string IsFastCrc32Supported() {
      |             ^~~~~~~~~~~~~~~~~~~~
In file included from util/crc32c.cc:12:
./util/crc32c.h:20:20: note: previous declaration with ‘C++’ linkage
   20 | extern std::string IsFastCrc32Supported();
      |                    ^~~~~~~~~~~~~~~~~~~~
util/crc32c.cc:1277:10: error: conflicting declaration of ‘uint32_t rocksdb::crc32c::Extend(uint32_t, const char*, size_t)’ with ‘C’ linkage
 1277 | uint32_t Extend(uint32_t crc, const char* buf, size_t size) {
      |          ^~~~~~
In file included from util/crc32c.cc:12:
./util/crc32c.h:25:17: note: previous declaration with ‘C++’ linkage
   25 | extern uint32_t Extend(uint32_t init_crc, const char* data, size_t n);
      |                 ^~~~~~
util/crc32c.cc:1283:1: error: expected ‘}’ at end of input
 1283 | }  // namespace ROCKSDB_NAMESPACE
      | ^
In file included from ./util/crc32c_arm64.h:16,
                 from util/crc32c.cc:21:
/usr/lib/gcc/aarch64-linux-gnu/9/include/arm_acle.h:33:12: note: to match this ‘{’
   33 | extern "C" {
      |            ^
make[2]: *** No rule to make target 'util/crc32c.o', needed by 'util/build_version.cc'.  Stop.
make[2]: Leaving directory '/home/ubuntu/ail-framework/kvrocks/external/rocksdb'
make[1]: *** [Makefile:129: /home/ubuntu/ail-framework/kvrocks/external/rocksdb/librocksdb.a] Error 2
make[1]: Leaving directory '/home/ubuntu/ail-framework/kvrocks/src'
make: *** [Makefile:7: all] Error 2
```

**Comment by vncloudsco** [comment]
We have released a more stable version on arm

**Comment by adulau** [comment]
@vncloudsco It's an old PR for the back-end which has been changed to kvrocks. So ARM is supported by default. Not sure why this PR was reopened.

**Pull request closed without merging**
